version: '2'

services:
    krb5_kiwitcms_org:
        container_name: krb5_kiwitcms_org
        image: kiwitcms/kerberos
        restart: always

    web_kiwitcms_org:
        container_name: web_kiwitcms_org
        image: kiwitcms/with-kerberos
        restart: always
        volumes:
            - web_kiwitcms_org_coverage:/coverage
            - ./social_auth_kerberos/:/venv/lib64/python3.11/site-packages/social_auth_kerberos/:z,ro

volumes:
    web_kiwitcms_org_coverage:
